import React from 'react';
import { Download, FileText, FileCode, Table, CheckCircle2, X } from 'lucide-react';
import { TimeMachineProject } from '../../types/timeMachine';

interface ExportReportModalProps {
  project: TimeMachineProject;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ project, onClose }) => {
  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    const md = `# AI TIME MACHINE HISTORICAL RECONSTRUCTION REPORT

## Project Overview
- **Name:** ${project.name}
- **Artifact Type:** ${project.artifactType}
- **Historical Coverage:** ${project.estimatedCoverage}
- **SHA-256 Hash:** ${project.fileHash}
- **Confidence Score:** ${project.confidenceScore}
- **Reconstructed Versions:** ${project.versionCount}

---

## Chronological Historical Timeline

${project.timelineEvents.map(e => `### ${e.date} — ${e.title}
- **Category:** ${e.type}
- **Confidence:** ${e.confidence.toUpperCase()} (${e.status})
- **Description:** ${e.description}
- **Evidence Sources:**
${e.evidence.map(ev => `  - [${ev.sourceType}] ${ev.sourceReference}: \`${ev.contentSnippet}\``).join('\n')}
`).join('\n\n')}

---

## Reconstructed Architecture Evolution
${project.reconstructedVersions.map(v => `- **Era ${v.yearLabel} (${v.versionTag}):** ${v.architecture.frontend || 'UI'} + ${v.architecture.backend || 'Backend'} (${v.filesCount} files tracked)`).join('\n')}

---

*Report generated by AI Time Machine — "Reconstruct history from evidence, not imagination."*
`;
    downloadFile(md, `${project.name.toLowerCase().replace(/\s+/g, '_')}_time_machine_report.md`, 'text/markdown');
  };

  const handleExportJSON = () => {
    const jsonStr = JSON.stringify(project, null, 2);
    downloadFile(jsonStr, `${project.name.toLowerCase().replace(/\s+/g, '_')}_timeline.json`, 'application/json');
  };

  const handleExportCSV = () => {
    const headers = 'Date,Title,Type,Confidence,Status,Description,EvidenceCount\n';
    const rows = project.timelineEvents.map(e => 
      `"${e.date}","${e.title.replace(/"/g, '""')}","${e.type}","${e.confidence}","${e.status}","${e.description.replace(/"/g, '""')}",${e.evidence.length}`
    ).join('\n');
    downloadFile(headers + rows, `${project.name.toLowerCase().replace(/\s+/g, '_')}_events.csv`, 'text/csv');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md">
      <div className="relative w-full max-w-lg bg-[#0c101a] border border-cyan-500/30 rounded-2xl p-6 shadow-2xl space-y-6 font-mono">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <Download className="w-5 h-5 text-cyan-400" />
            <h2 className="font-bold text-slate-100 text-sm">EXPORT RECONSTRUCTION REPORT</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-200">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-3">
          <button
            onClick={handleExportMarkdown}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-cyan-500/40 transition-all text-xs text-left"
          >
            <div className="flex items-center space-x-3">
              <FileText className="w-5 h-5 text-amber-400" />
              <div>
                <span className="font-bold text-slate-100 block">Markdown Research Report (.md)</span>
                <span className="text-[11px] text-slate-400">Human-readable audit documentation with evidence lines.</span>
              </div>
            </div>
            <Download className="w-4 h-4 text-cyan-400" />
          </button>

          <button
            onClick={handleExportJSON}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-cyan-500/40 transition-all text-xs text-left"
          >
            <div className="flex items-center space-x-3">
              <FileCode className="w-5 h-5 text-cyan-400" />
              <div>
                <span className="font-bold text-slate-100 block">Machine-Readable Timeline (.json)</span>
                <span className="text-[11px] text-slate-400">Full structured timeline schema & evidence graph.</span>
              </div>
            </div>
            <Download className="w-4 h-4 text-cyan-400" />
          </button>

          <button
            onClick={handleExportCSV}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-cyan-500/40 transition-all text-xs text-left"
          >
            <div className="flex items-center space-x-3">
              <Table className="w-5 h-5 text-emerald-400" />
              <div>
                <span className="font-bold text-slate-100 block">CSV Timeline Events Table (.csv)</span>
                <span className="text-[11px] text-slate-400">Tabular format for Excel & data analysis.</span>
              </div>
            </div>
            <Download className="w-4 h-4 text-cyan-400" />
          </button>
        </div>
      </div>
    </div>
  );
};
